source 'https://rubygems.org'

gem 'rails', '~> 7.1'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 6.0'

# ActiveIntelligence - use local gem for development
gem 'activeintelligence.rb', path: '../..'

# For API calls (Bible API)
gem 'httparty', '~> 0.21'

group :development do
  gem 'listen', '~> 3.8'
  gem 'pry'
end
